### ISSUE TITLE
Can this be used with typescript?

### ISSUE THREAD

**Issue by panda0603** [Financial-Times/js-features-analyser#34]
First of all thanks for the library. 

Can this be used with typescript, i.e. file extensions with .ts or .tsx that contains type syntax?

**Comment by chee** [comment]
you'd want to use it on the compiled bundle produced by TypeScript's compiler.

different versions of TypeScript would compile the same code to use different features. that is also true for the same version of TypeScript with different tsconfig options or command line options.

so you will want to compile the code, and then analyze it
