### ISSUE TITLE
Data source of global-static-instance.json

### ISSUE THREAD

**Issue by panda0603** [Financial-Times/js-features-analyser#40]
Hello, 

May I ask where the source of global-static-instance.json file is retrieved from? 

It seems to be a static data, which means it wouldn't be updated unless maintainer or someone manually adds data to it when new specs are added. 

What happens when new specs are added? 

Thanks

**Comment by JakeChampion** [comment]
Yes, I manually update it 👍

**Comment by panda0603** [comment]
oh okay.
may I ask How often you update it? where is the source from?

**Comment by JakeChampion** [comment]
The source if generated by this gist -- https://gist.github.com/JakeChampion/153cb12e4c61da3d2cf43fb3fd70cd66

I update it when polyfill-library project adds polyfills for new JavaScript features

**Comment by chee** [comment]
hopefully that answers your question :) if it doesn't, feel free to reopen
