### ISSUE TITLE
How to use with browserlist and a polyfill library

### ISSUE THREAD

**Issue by jdart** [Financial-Times/js-features-analyser#60]
Thanks for this great tool! Do you have any guidance on using this with polyfill.io or core-js based on some browserlist configuration?

**Comment by JakeChampion** [comment]
Hi @jdart, I would use [create-polyfill-service-url](https://www.npmjs.com/package/create-polyfill-service-url) to create a polyfill.io url based on a browserlist configuration.

js-features-analyser is a lower level tool which is used internally by [create-polyfill-service-url](https://www.npmjs.com/package/create-polyfill-service-url)
