### ISSUE TITLE
I have got an Error: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by Awen-hub** [Financial-Times/js-features-analyser#95]
Here is my file content:
`
var a = [{ b: 2, c: 3 }];
for (const { b: d, c: e } of a) {};
`

When I run the "npx create-polyfill-service-url analyse --file", it shows me an Error:"Cannot read property 'name' of null". I have found that the error occurs in feature.js in line 205. In this case the obj will be null. I am also willing to help to fix this bug.

**Comment by JakeChampion** [comment]
Hi @Awen-hub. thanks for the issue, would you be able to open a pull-request which adds a test case for this?
To add a test you will need to make a folder in `/test/fixtures/` and a file in that folder named `code.js` which contains the code to test, and finally, a file named `expected.json` which contains an empty json array `[]`.

With that test available, we can then figure out how to make it pass :-)

**Comment by Awen-hub** [comment]
> Hi @Awen-hub. thanks for the issue, would you be able to open a pull-request which adds a test case for this?
> To add a test you will need to make a folder in `/test/fixtures/` and a file in that folder named `code.js` which contains the code to test, and finally, a file named `expected.json` which contains an empty json array `[]`.
> 
> With that test available, we can then figure out how to make it pass :-)

Great. It's my pleasure to do it, but I find that I have no permission to push a branch in this repository. Could you please give me a permission?

**Comment by JakeChampion** [comment]
@Awen-hub We don't hand out permissions to this repository, sorry. You should be able to fork the repository and create a pull-request from your fork. GitHub have a guide for how to fork a project and create a pull-request which might be useful if you have not used this type of workflow previously -- https://guides.github.com/activities/forking/

**Comment by Awen-hub** [comment]
> @Awen-hub We don't hand out permissions to this repository, sorry. You should be able to fork the repository and create a pull-request from your fork. GitHub have a guide for how to fork a project and create a pull-request which might be useful if you have not used this type of workflow previously -- https://guides.github.com/activities/forking/

Thanks for your detailed guide and I have created a pull-request.

**Comment by Awen-hub** [comment]
> @Awen-hub We don't hand out permissions to this repository, sorry. You should be able to fork the repository and create a pull-request from your fork. GitHub have a guide for how to fork a project and create a pull-request which might be useful if you have not used this type of workflow previously -- https://guides.github.com/activities/forking/

Is there any progress about this issue？

**Comment by Awen-hub** [comment]
@JakeChampion

**Comment by Awen-hub** [comment]
> @JakeChampion

hello? In fact I find it is not so hard to fix this problem and I want to use the tool "create-polyfill-service-url" in production recently. So Can I create another pull-request to fix it?

**Comment by JakeChampion** [comment]
Yes, I'll gladly review a pull request to fix this

**Comment by Awen-hub** [comment]
> Yes, I'll gladly review a pull request to fix this

Great. I do it right now.

**Comment by JakeChampion** [comment]
Thanks for the pull-request @Awen-hub - this was released in version 0.4.3 👍

**Comment by Awen-hub** [comment]
> Thanks for the pull-request @Awen-hub - this was released in version 0.4.3 👍

Thanks for the detailed guide with @JakeChampion too 👍
